In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
loans = pd.read_csv('data/ml_source_files/loan_data.csv')
loans.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [6]:
loans.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   credit.policy      9578 non-null   int64  
 1   purpose            9578 non-null   object 
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64  
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64  
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64  
 11  delinq.2yrs        9578 non-null   int64  
 12  pub.rec            9578 non-null   int64  
 13  not.fully.paid     9578 non-null   int64  
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [7]:
# 대출 가능여부를 판단 - 모델을 생성 .. 
# 데이터 - 고객의 특성에 따라 default 여부가 있는 데이터 

In [ ]:
# decisiontree, randomforest를 통해서 예측모델 생성, 테스트..  

In [17]:
y = loans['not.fully.paid']
x = loans.drop(['not.fully.paid','purpose'],axis = 1)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=111)

In [19]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()

In [20]:
tree.fit(x_train,y_train)

DecisionTreeClassifier()

In [30]:
preds = tree.predict(x_test)
preds

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import classification_report,precision_score,f1_score,recall_score
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           0       0.87      0.83      0.85      1635
           1       0.22      0.27      0.24       281

    accuracy                           0.75      1916
   macro avg       0.54      0.55      0.55      1916
weighted avg       0.77      0.75      0.76      1916



In [23]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=500)

In [24]:
rfc.fit(x_train,y_train)
preds_rfc = rfc.predict(x_test)
print(classification_report(y_test,preds_rfc))

              precision    recall  f1-score   support

           0       0.85      0.99      0.92      1635
           1       0.31      0.01      0.03       281

    accuracy                           0.85      1916
   macro avg       0.58      0.50      0.47      1916
weighted avg       0.77      0.85      0.79      1916



In [27]:
loans.columns

Index(['credit.policy', 'purpose', 'int.rate', 'installment', 'log.annual.inc',
       'dti', 'fico', 'days.with.cr.line', 'revol.bal', 'revol.util',
       'inq.last.6mths', 'delinq.2yrs', 'pub.rec', 'not.fully.paid'],
      dtype='object')

In [28]:
tree.feature_importances_

array([0.02677803, 0.10739045, 0.13560256, 0.11006209, 0.1253363 ,
       0.06804358, 0.1528099 , 0.10516826, 0.10809472, 0.03983107,
       0.01228035, 0.00860271])

In [29]:
rfc.feature_importances_

array([0.01571159, 0.10955808, 0.12278265, 0.11627979, 0.11601135,
       0.08166783, 0.12024608, 0.11823162, 0.11748606, 0.05732994,
       0.01535931, 0.00933568])

In [31]:
# gridsearch 

In [32]:
from sklearn.model_selection import GridSearchCV

params = {'n_estimators': [50,100,500,1000],
         'max_depth': [10,20,50,100],
         'min_samples_leaf':[2,3,5]}

rfc = RandomForestClassifier()
grid = GridSearchCV(rfc,param_grid= params, refit=True, verbose=True)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 50, 100],
                         'min_samples_leaf': [2, 3, 5],
                         'n_estimators': [50, 100, 500, 1000]},
             verbose=True)

In [33]:
grid.best_params_

{'max_depth': 50, 'min_samples_leaf': 5, 'n_estimators': 1000}

In [34]:
grid.best_score

AttributeError: 'GridSearchCV' object has no attribute 'best_score'